FROM node:lts-buster

RUN apt-get update
#    apt-get install vim -y && \
#    groupadd -g 1000 app_user && \
#    useradd -m -s /bin/bash -u 1000 -g 1000 app_user
#RUN mkdir -p /opt/app && chown -R app_user:app_user /opt/app
#RUN mkdir -p /opt/app && chown -R 1000:1000 /opt/app
WORKDIR /opt/app

#USER app_user
#USER 1000

